#!/bin/bash

## 获取MobileSubstrate目录下的tersafe文件路径
#tersafe_path="/Library/MobileSubstrate/DynamicLibraries/tersafe"
#
## 查找ShadowTrackerExtra.app目录
#st_app_path="$(find /var/containers/Bundle/Application -name "ShadowTrackerExtra.app" -type d)"
#
## 检查是否找到ShadowTrackerExtra.app目录
#if [[ -z "$st_app_path" ]]; then
#  echo "未找到ShadowTrackerExtra.app目录"
#  exit 1
#fi
#
## 拷贝tersafe文件到ShadowTrackerExtra.app/Framework/tersafe.framework
#cp "$tersafe_path" "$st_app_path/Frameworks/tersafe.framework/tersafe"

# 打印操作完成消息
echo "安装完成-请注销设备生效-游戏中按音量键激活"
